AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MetaWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meta_webhook
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 256
        
